name: Build (CUDA - no GPU)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.4.1-devel-ubuntu22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt install -y cmake ninja-build build-essential

      - name: Configure and Build with CMake + Ninja
        run: |
          rm -rf build
          mkdir -p build
          cd build
          
          if nvidia-smi > /dev/null 2>&1; then
            echo "GPU detected. Enabling CUDA."
            CUDA_ARGS="-DGGML_CUDA=ON -DGGML_CUDA_FORCE_CUBLAS=ON"
          else
            echo "No GPU detected. Disabling CUDA."
            CUDA_ARGS="-DGGML_CUDA=OFF"
          fi
          
          cmake .. -G Ninja -DGGML_CUDA=OFF
          ninja

      - name: Mark build successful (no GPU testing)
        run: echo "Build successful. GPU testing is skipped on CI. No way Jose."
