name: Build (Rust - llamars)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: llamars

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Build llamars crate
        run: cargo build --release

      - name: Run Clippy (linter of pain)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests (if any)
        run: cargo test || echo "No tests yet, skipping."

      - name: Mark success
        run: echo "llamars Rust crate built successfully

      - name: Check formatting
        run: cargo fmt --all -- --check